# Generated by Django 3.2.3 on 2021-05-20 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_alter_venue_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='place',
            new_name='location',
        ),
    ]
