# Generated by Django 3.2.3 on 2021-05-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_rename_place_venue_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Hotel cost'),
            preserve_default=False,
        ),
    ]
