# Generated by Django 3.2.3 on 2021-05-27 16:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0005_venue_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsOrganize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Event title')),
                ('description', tinymce.models.HTMLField(verbose_name='Event description')),
                ('image', models.ImageField(upload_to='', verbose_name='Event image')),
                ('price', models.PositiveIntegerField(verbose_name='Event price')),
            ],
        ),
        migrations.CreateModel(
            name='FrontendInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField(verbose_name='Official phone number')),
                ('active_hour', models.CharField(max_length=150, verbose_name='Office active hours')),
                ('first_banner', models.ImageField(upload_to='', verbose_name='Frontend main banner')),
                ('banner_title', models.CharField(max_length=150, verbose_name='Frontend main banner title')),
                ('banner_subtitle', models.CharField(max_length=150, verbose_name='Frontend main banner subtitle')),
                ('description', tinymce.models.HTMLField(verbose_name='EBM description')),
                ('login_background', models.ImageField(upload_to='', verbose_name='Login background')),
                ('description_image', models.ImageField(upload_to='', verbose_name='EBM description image')),
                ('description_banner', models.ImageField(upload_to='', verbose_name='EBM description banner')),
                ('location', models.CharField(max_length=150, verbose_name='Office location')),
                ('email', models.EmailField(max_length=150, verbose_name='Office email')),
                ('twitter', models.CharField(max_length=150, verbose_name='Our official twitter')),
                ('facebook', models.CharField(max_length=150, verbose_name='Our official facebook')),
                ('instagram', models.CharField(max_length=150, verbose_name='Our official instagram')),
                ('linkedin', models.CharField(max_length=150, verbose_name='Our official linkedin')),
                ('google_plus', models.CharField(max_length=150, verbose_name='Our official google-plus')),
            ],
        ),
        migrations.CreateModel(
            name='MessageUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='User name')),
                ('email', models.EmailField(max_length=254, verbose_name='User email')),
                ('subject', models.CharField(max_length=150, verbose_name='Message subject')),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Package title')),
                ('subtitle', models.CharField(max_length=150, verbose_name='Package small description')),
                ('description', tinymce.models.HTMLField(verbose_name='Package description')),
                ('image', models.ImageField(upload_to='', verbose_name='Package image')),
                ('package_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Package initial cost')),
            ],
        ),
        migrations.CreateModel(
            name='PackageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Package type name')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Team member name')),
                ('role', models.CharField(max_length=150, verbose_name='Team member role')),
                ('image', models.ImageField(upload_to='', verbose_name='Team member image')),
                ('twitter', models.CharField(max_length=150, verbose_name='Team member twitter account name')),
                ('facebook', models.CharField(max_length=150, verbose_name='Team member facebook account name')),
                ('instagram', models.CharField(max_length=150, verbose_name='Team member instagram account name')),
                ('linkedin', models.CharField(max_length=150, verbose_name='Team member linkedin account name')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11)),
                ('location', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PackageFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('religion', models.CharField(max_length=150)),
                ('food', tinymce.models.HTMLField(verbose_name='Food lists')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price per person')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_foods', to='frontend_app.package')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_package', to='frontend_app.packagetype'),
        ),
        migrations.CreateModel(
            name='EventBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(choices=[(datetime.time(10, 0), datetime.time(10, 0)), (datetime.time(16, 0), datetime.time(16, 0))], max_length=13)),
                ('people', models.PositiveIntegerField()),
                ('message', models.TextField()),
                ('accept', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('my_venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_book', to='admin_app.venue')),
                ('package', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_book', to='frontend_app.package')),
                ('package_food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_food_related', to='frontend_app.packagefood')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_book', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CheckoutInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_id', models.SlugField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cart_type', models.CharField(max_length=150)),
                ('transaction_date', models.DateTimeField()),
                ('bank_transaction_id', models.CharField(max_length=150)),
                ('event_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_checkout', to='frontend_app.eventbook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_checkout', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
