# Generated by Django 3.2.3 on 2021-05-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_app', '0002_alter_packagefood_religion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagefood',
            name='religion',
            field=models.CharField(choices=[('islam', 'Islam'), ('hindu', 'Hindu'), ('christan', 'Christan'), ('buddha', 'Buddha')], max_length=150),
        ),
    ]
