# Generated by Django 3.2.3 on 2021-05-28 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_app', '0003_alter_packagefood_religion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbook',
            name='package_food',
            field=models.ForeignKey(blank=True, limit_choices_to={'package': models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_book', to='frontend_app.package')}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_food_related', to='frontend_app.packagefood'),
        ),
    ]
