# Generated by Django 3.2.3 on 2021-05-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_app', '0005_alter_eventbook_package_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagefood',
            name='food',
            field=models.CharField(max_length=150, verbose_name='Food lists'),
        ),
    ]
