# Generated by Django 3.2.3 on 2021-05-28 12:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_app', '0007_alter_packagefood_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbook',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, null=True),
        ),
    ]
