# Generated by Django 3.2.3 on 2021-05-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_app', '0008_eventbook_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontendinfo',
            name='checkout_background',
            field=models.ImageField(default=1, upload_to='', verbose_name='Checkout background'),
            preserve_default=False,
        ),
    ]
